spring:
  datasource:
    url: jdbc:mysql://mysql.stinfo.orb.local/auth_service?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: 1
      host: redis.stinfo.orb.local
      port: 6379
      #      password:
      timeout: 10s
      connect-timeout: 10s

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.personal.project.authservice.model.entity