spring:
  datasource:
    url: jdbc:mysql://mysql.stinfo.orb.local/stock_service?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.personal.project.stockservice.model.entity
  type-handlers-package: com.personal.project.stockservice.typehandler
