spring:
  datasource:
    url: jdbc:mysql://mysql.stinfo.orb.local/report_service?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.personal.project.reportservice.model.entity

xxl:
  job:
    enabled: true
    accessToken: personal
    admin:
      addresses: http://xxl-job-admin.stinfo.orb.local/xxl-job-admin
    executor:
      appName: report-service
      #      address:
      #      ip:
      #      port:
      logpath: /app/logs/xxl
      logretentiondays: 7