spring:
  datasource:
    url: jdbc:mysql://mysql.stinfo.orb.local/gateway?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: 0
      host: redis.stinfo.orb.local
      port: 6379
      #      password:
      timeout: 10s
      connect-timeout: 10s

  rabbitmq:
    host: rabbitmq.stinfo.orb.local
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.personal.project.gateway.model.entity

custom:
  gateway:
    skip:
      visit:
        - /gw/auth/p/login
        - /gw/report/util/tags
        - /gw/stock/p/main-page
        - /gw/stock/p/real-time-page
        - /gw/chat/tg/command
      auth:
        - /gw/auth/p/login
        - /gw/auth/sign/sign-in
        - /gw/auth/sign/sign-up
        - /gw/chat/tg/command