spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      #      password:
      timeout: 10s
      connect-timeout: 10s

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.personal.project.gateway.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

custom:
  gateway:
    skip:
      visit:
        - /gw/report/util/tags
        - /gw/chat/tg/command
      auth:
        - /gw/auth/sign/check-token
        - /gw/auth/sign/sign-in
        - /gw/auth/sign/sign-up
        - /gw/chat/tg/command