spring:
  datasource:
    url: jdbc:mysql://mysql.stinfo.orb.local/scraper_service?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: 2
      host: redis.stinfo.orb.local
      port: 6379
      #      password:
      timeout: 10s
      connect-timeout: 10s

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.personal.project.scraperservice.model.entity
  type-handlers-package: com.personal.project.scraperservice.typehandler

xxl:
  job:
    #    enabled: true
    accessToken: personal
    admin:
      addresses: http://xxl-job-admin.stinfo.orb.local/xxl-job-admin
    executor:
      appName: scraper-service
      #      address:
      #      ip:
      #      port:
      logpath: /app/logs/xxl
      logretentiondays: 7

scraper:
  resource:
    driver: firefox
    browserpath:
    driverpath: /app/browser/driver/geckodriver
