spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scraper_service?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Taipei
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      database: 2
      host: localhost
      port: 6379
      #      password:
      timeout: 10s
      connect-timeout: 10s

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.personal.project.scraperservice.model.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-handlers-package: com.personal.project.scraperservice.typehandler

#logging:
#  level:
#    com.personal.project.stockservice.mapper: debug

xxl:
  job:
#    enabled: true
    accessToken: personal
    admin:
      addresses: http://127.0.0.1:8998/xxl-job-admin
    executor:
      appName: scraper-service
#      address:
#      ip:
#      port:
      logpath:
      logretentiondays:

scraper:
  resource:
    driver:
    browserpath:
    driverpath: